### ISSUE TITLE
Volume Groups not currently supported

### ISSUE THREAD

**Issue by IanSim2012** [fiddyschmitt/clonezilla-util#10]
Hello,
I'm getting the following exception:

```
clonezilla-util.exe mount --input "D:\Disk Images\Nextcloud Server\2022-08-25" --mount L:\

[04:14:10 INF] clonezilla-util v1.7.1
[04:14:11 INF] [2022-08-25] [sdb1] Finding optimal decompressor (seekable/sequential)
[04:14:11 INF] [2022-08-25] [sdb1] Loading partition information
[04:14:11 INF] [2022-08-25] [sdb1] Reading partclone content map
[04:14:11 INF] [2022-08-25] [sdb2] Finding optimal decompressor (seekable/sequential)
[04:14:13 INF] [2022-08-25] [sdb2] Loading partition information
[04:14:13 INF] [2022-08-25] [sdb2] Reading partclone content map
Unhandled exception. System.Exception: Could not determine compression used by partition sdb3.*-ptcl-img in: D:\Disk Images\Nextcloud Server\2022-08-25
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String clonezillaArchiveFolder, String filenamePattern)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__2(String partitionName)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

I don't know if it is actually an unknown compression error because I used the default parallel gzip (**-z1p**) option and the other two partitions seem to have been recognized properly.

The image was created using the following command (as stored in the Clonezilla _Info-saved-by-cmd.txt_ file):
`/usr/sbin/ocs-sr -q2 -c -j2 -gm -z1p -i 100000000 -sfsck -senc -p reboot savedisk 2022-08-25 sdb`

Could you please check this issue?

Many thanks in advance!

**Comment by fidel-planbuddies** [comment]
Thanks for reaching out Ian :)

Yes it's curious it opened `sdb1` and `sdb2` without issue.

The compression format is deduced from the filename. Could you please let me know the filenames which start with sdb3?

Thanks,
Fidel

**Comment by IanSim2012** [comment]
Actually, there are no files starting with `sdb3`...
The image file related to the `sdb3 `partition is called `ubuntu-vg-ubuntu-lv.ext4-ptcl-img.gz.aa`.

Here is the list of the image files related to all the available partitions:
- sdb1.vfat-ptcl-img.gz.aa
- sdb2.ext4-ptcl-img.gz.aa
- ubuntu-vg-ubuntu-lv.ext4-ptcl-img.gz.aa

As stated in my first post, I think that the exception message is misleading and the actual exception is thrown due to the file not found instead of an unknown compression algorithm.

For further information, you can find below the list of all the available block devices as reported by the command `lsblk -e7`:
```
NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                         8:0    0 298.1G  0 disk
├─sda1                      8:1    0 298.1G  0 part
└─sda9                      8:9    0     8M  0 part
sdb                         8:16   0  29.8G  0 disk
├─sdb1                      8:17   0   512M  0 part /boot/efi
├─sdb2                      8:18   0     1G  0 part /boot
└─sdb3                      8:19   0  28.3G  0 part
  └─ubuntu--vg-ubuntu--lv 253:0    0  28.3G  0 lvm  /
```

Thank you very much for your support!
Simone

**Comment by fiddyschmitt** [comment]
Thanks Simone!
Yes the program reads the `parts` files to get a list of partitions, then tries to search for each one using wildcards (which also helps derive the compression type). I'll update the messaging so it's not misleading, and look into how to support Volume Groups.

Thanks Simone,
Fidel

**Comment by IanSim2012** [comment]
Great!

Thank you very much!
Simone

**Comment by fiddyschmitt** [comment]
Hi Simone,

Could you please post the contents of `blkdev.list`?

Thanks,
Fidel

**Comment by IanSim2012** [comment]
Hi Fidel,
sure, here it is:
```
KNAME NAME     SIZE TYPE FSTYPE      MOUNTPOINT                                     MODEL
loop1 loop1  264.9M loop squashfs    /usr/lib/live/mount/rootfs/filesystem.squashfs 
sda   sda    298.1G disk                                                            ST9320325AS
sda1  |-sda1 298.1G part zfs_member                                                 
sda9  `-sda9     8M part                                                            
sdb   sdb     29.8G disk                                                            SQF-SMSM4-32G-S9C
sdb1  |-sdb1   512M part vfat                                                       
sdb2  |-sdb2     1G part ext4                                                       
sdb3  `-sdb3  28.3G part LVM2_member                                                
sdc   sdc     14.6G disk                                                            Transcend 16GB
sdc1  `-sdc1  14.6G part vfat                                                       
```

Thanks,
Simone

**Comment by fiddyschmitt** [comment]
Thanks!
Testing the update now. It should be online in the next 24 hours.

**Comment by IanSim2012** [comment]
Hi Fidel,
I've just tested the new version, but unfortunately, after the partition has been extracted, I got the following exception:
```
...
[00:05:32 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Cached 9,22 GB. (100% through source file)
[00:05:32 INF] Successfully cached to: E:\clonezilla-util\cache\0aebc97062c8169bda84f8cb45f70f8d\cache.train
[00:05:33 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Loading partition information
[00:05:33 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Reading partclone content map
[00:05:33 INF] Waiting for L:\ to be available.
[00:05:33 INF] [2022-08-25] [sdb1] Retrieving a list of files.
Unhandled exception. System.Exception: E:\clonezilla-util\ext\7-Zip\win-x64\7z.exe l "L:\ff903c91-37de-4bba-bcb3-afb72bab1cd4 - Temp\b5c9f591-043d-4536-b643-6c5e0e3cc3f3\sdb1.img"
Process encountered errors:
ERROR: L:\ff903c91-37de-4bba-bcb3-afb72bab1cd4 - Temp\b5c9f591-043d-4536-b643-6c5e0e3cc3f3\sdb1.img : Cannot open the file as archive


   at libCommon.ProcessUtility.RunCommand(String cpath, String args, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`2 shouldStop)+MoveNext()
   at lib7Zip.SevenZipUtility.IsArchive(String filename)
   at libClonezilla.Partitions.MountedPartitionImage.GetTree()
   at libClonezilla.Partitions.MountedPartitionImage..ctor(Partition partition, Folder partitionFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Partitions.MountedContainer.<>c__DisplayClass0_0.<.ctor>b__0(Partition partition)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Partitions.MountedContainer..ctor(PartitionContainer container, Folder containerFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Utility.<>c__DisplayClass1_0.<PopulateVFS>b__1(PartitionContainer container)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Utility.PopulateVFS(IVFS vfs, Folder containersRoot, List`1 containers, DesiredContent desiredContent)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

Observing the system during the process, it seems that it was unable to mount the drive `L:\`..,
The Dokan Driver (v1.5.1.1000) is installed, of course.

Furthermore, as perhaps already stated in issue #12, it seems that extracting partition files takes a little long, as shown by the log below:
```
...
2022-09-19 23:54:17.468 +02:00 [INF] Creating cache file: E:\clonezilla-util\cache\0aebc97062c8169bda84f8cb45f70f8d\cache.train
2022-09-19 23:54:17.506 +02:00 [INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Cached 193,4 KB. (0% through source file)
...
2022-09-20 00:05:32.500 +02:00 [INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Cached 9,22 GB. (100% through source file)
2022-09-20 00:05:32.518 +02:00 [INF] Successfully cached to: E:\clonezilla-util\cache\0aebc97062c8169bda84f8cb45f70f8d\cache.train
...
```
As a side note, a little bug (or maybe as per designed?) on log file creation: if the process is already running at the turn of midnight, the log is splitted on two different files with different date.

Again many thanks for your effort,
Simone

**Comment by fiddyschmitt** [comment]
My pleasure, thank you for testing!

Oh interesting - it seems to have a problem inspecting `sdb1`. To skip that partition, could you please try:

`clonezilla-util.exe mount --input "D:\Disk Images\Nextcloud Server\2022-08-25" --mount L:\ -p "ubuntu-vg-ubuntu-lv"`

Thanks!

p.s. yes the midnight rollover of the log file is by design :)

**Comment by IanSim2012** [comment]
Hi Fidel,
thank you very much for your hint! Now the partition mounts properly!

However, even if I can browse the folders and see the files, I get the following error when I try to copy a file on a local hard drive:
`Error 0x80070057: Invalid argument`

I guess that this error is probably related to the Dokan Driver and not to your application, but maybe you can give me a hint on how to fix this issue...

I also have to say that there is still an error shown by the application log:
```
...
[09:39:23 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Loading partition information
[09:39:24 INF] Waiting for L:\ to be available.
[09:39:24 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] Retrieving a list of files.
[09:39:47 INF] [2022-08-25] [ubuntu-vg-ubuntu-lv] 7zFM.exe will be used to extract files from this partition.
[09:40:25 ERR] Could not find [SYS] in System.Collections.Generic.Dictionary`2[System.String,libDokan.VFS.Folders.Folder]
[09:40:25 INF] Mounting complete. Mounted to: L:\
```
One more question: are you aware of a seekable compression option supported by both Clonezila and your application? This would allow me to mount the whole partition without extracting the files first. As I stated in my previous post, the extraction operation takes a while even for relatively small partitions.

Thank you again,
Simone

**Comment by fiddyschmitt** [comment]
Thanks Simone,

I haven't seen the `0x80070057` error before. Rather than mounting the Clonezilla archive, it might be worth extracting it, which doesn't require Dokan:

`clonezilla-util.exe extract-partition-image --input "D:\Disk Images\Nextcloud Server\2022-08-25" --output "D:\Disk Images\Nextcloud Server\2022-08-25_extracted"`

The `Could not find [SYS]` is normal, it's just related to that particular file system.

Unfortunately none of the compression options in Clonezilla are seekable, which is why my application has to first extract into a cache file. It would be nice if Clonezilla did implement that feature though. I'll raise a feature request.

Cheers,
Fidel

**Comment by fiddyschmitt** [comment]
Requested the following over at Clonezilla:

[Feature request: Seekable compression format](https://github.com/stevenshiau/clonezilla/issues/76)

**Comment by IanSim2012** [comment]
Hi Fidel,
thank you very much for all your efforts and suggestions! I really appreciate it!
I consider this issue closed.

Cheers,
Simone

**Comment by fiddyschmitt** [comment]
:) My pleasure! Thanks Simone!
