### ISSUE TITLE
Unknown partclone image version

### ISSUE THREAD

**Issue by YoykoKoszko** [fiddyschmitt/clonezilla-util#21]
Hi, sorry if I am asking noon questions but where do I run the command? In cmd? Or in the clonezilla-util?

**Comment by fiddyschmitt** [comment]
Hi Yoyko,

Yes just open `cmd` first, then change into the appropriate folder eg. `cd C:\Downloads\clonezilla-util` then you can run commands.

Please let me know how you go :)

Cheers,
Fidel

**Comment by YoykoKoszko** [comment]
> Hi Yoyko,
> 
> Yes just open `cmd` first, then change into the appropriate folder eg. `cd C:\Downloads\clonezilla-util` then you can run commands.
> 
> Please let me know how you go :)
> 
> Cheers, Fidel

I manged to run the command but drive is not mounted:

`C:\Users\Wiecz\Downloads\Nowy folder>clonezilla-util.exe mount --input D:\Backup\2022-11-05-16-imgwindows11 --mount L:\
[11:12:38 INF] clonezilla-util v2.0.1
[11:12:38 INF] [2022-11-05-16-imgwindows11] [nvme0n1p1] Finding optimal decompressor (seekable/sequential)
[11:12:40 INF] [2022-11-05-16-imgwindows11] [nvme0n1p1] Loading partition information
[11:12:40 INF] [2022-11-05-16-imgwindows11] [nvme0n1p2] Finding optimal decompressor (seekable/sequential)
[11:12:40 INF] [2022-11-05-16-imgwindows11] [nvme0n1p2] Loading partition information
[11:12:40 ERR] [2022-11-05-16-imgwindows11] [nvme0n1p2] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[11:12:40 INF] [2022-11-05-16-imgwindows11] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[11:12:52 INF] [2022-11-05-16-imgwindows11] [nvme0n1p3] Loading partition information
[11:12:53 ERR] [2022-11-05-16-imgwindows11] [nvme0n1p3] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[11:12:53 INF] [2022-11-05-16-imgwindows11] [nvme0n1p4] Finding optimal decompressor (seekable/sequential)
[11:13:00 INF] [2022-11-05-16-imgwindows11] [nvme0n1p4] Loading partition information
[11:13:00 INF] [2022-11-05-16-imgwindows11] [nvme0n1p5] Finding optimal decompressor (seekable/sequential)
[11:13:10 INF] [2022-11-05-16-imgwindows11] [nvme0n1p5] Loading partition information
[11:13:10 INF] [2022-11-05-16-imgwindows11] [nvme0n1p6] Finding optimal decompressor (seekable/sequential)
[11:13:13 INF] [2022-11-05-16-imgwindows11] [nvme0n1p6] Loading partition information
[11:13:13 INF] Waiting for L:\ to be available.
[11:13:13 INF] [2022-11-05-16-imgwindows11] [nvme0n1p1] Retrieving a list of files.
Unhandled exception. System.Exception: C:\Users\Wiecz\Downloads\Nowy folder\ext\7-Zip\win-x64\7z.exe l "L:\5b17fe1d-de85-408a-9530-9348dbf664b5 - Temp\36f48156-26ae-4f1e-b249-7dcd9491d1f1\nvme0n1p1.img"
Process encountered errors:
ERROR: L:\5b17fe1d-de85-408a-9530-9348dbf664b5 - Temp\36f48156-26ae-4f1e-b249-7dcd9491d1f1\nvme0n1p1.img : Cannot open the file as archive


   at libCommon.ProcessUtility.RunCommand(String cpath, String args, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`2 shouldStop)+MoveNext()
   at lib7Zip.SevenZipUtility.IsArchive(String filename)
   at libClonezilla.Partitions.MountedPartitionImage.GetTree()
   at libClonezilla.Partitions.MountedPartitionImage..ctor(Partition partition, Folder partitionFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Partitions.MountedContainer.<>c__DisplayClass0_0.<.ctor>b__0(Partition partition)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Partitions.MountedContainer..ctor(PartitionContainer container, Folder containerFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Utility.<>c__DisplayClass1_0.<PopulateVFS>b__1(PartitionContainer container)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Utility.PopulateVFS(IVFS vfs, Folder containersRoot, List`1 containers, DesiredContent desiredContent)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
`

**Comment by YoykoKoszko** [comment]
mounting image got 3 partitions but for the main one i get 

`[11:12:40 INF] [2022-11-05-16-imgwindows11] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[11:12:52 INF] [2022-11-05-16-imgwindows11] [nvme0n1p3] Loading partition information
[11:12:53 ERR] [2022-11-05-16-imgwindows11] [nvme0n1p3] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)`

**Comment by fiddyschmitt** [comment]
Thanks Yoyko,

Could you please upload the `clonezilla-img` file?

Thanks!
Fidel

**Comment by fiddyschmitt** [comment]
Actually, the latest version ([2.0.3](https://github.com/fiddyschmitt/clonezilla-util/releases)) should get past the problem you reported.

**Comment by Alexbanul** [comment]
Hi, I think I get the same error with 2.0.3
After the disk was mounted I was able to access 2 out of 4 partitions avalilable on the disk; 
`clonezilla-util.exe mount --input G:\Backup\20221121\2022-11-21-18-img --mount L:\
[09:42:54 INF] clonezilla-util v2.0.3
[09:42:55 INF] [2022-11-21-18-img] [nvme0n1p1] Finding optimal decompressor (seekable/sequential)
[09:42:55 INF] [2022-11-21-18-img] [nvme0n1p1] Loading partition information
[09:42:55 INF] [2022-11-21-18-img] [nvme0n1p1] Reading partclone content map
[09:42:56 INF] [2022-11-21-18-img] [nvme0n1p2] Finding optimal decompressor (seekable/sequential)
[09:42:56 INF] [2022-11-21-18-img] [nvme0n1p2] Loading partition information
[09:42:56 ERR] [2022-11-21-18-img] [nvme0n1p2] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[09:42:56 INF] [2022-11-21-18-img] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[09:43:06 INF] Generating gzip index.
ACTION: Create index for a gzip file

Processing STDIN ...
Processing index to 'C:\Apps\clonezilla-util\cache\f8bdf4a4c079f47f\nvme0n1p3.gztool_index.gzi.wip'...
[09:43:07 INF] Indexed 50 MB / 85,29 GB (0%)`

**Comment by litscham** [comment]
Got the same error, also on 2.03 with an image from an opensuse system
I also tried a NTFS  image and it worked without a problem, so maybe it has to do with BTRFS?

Here is the clonezilla-img of the image that did not work:
```
This image was saved by Clonezilla at 2020-07-08 15:30:42 UTC.
Saved by clonezilla-live-2.6.7-28-amd64.
The log during saving:
----------------------------------------------------------
Starting /usr/sbin/ocs-sr at 2020-07-08 15:06:26 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: sdb
*****************************************************.
The selected devices: sdb
Searching for data/swap/extended partition(s)...
The data partition to be saved: sdb1 sdb3 sdb4
The swap partition to be saved: sdb5
The selected devices: sdb1 sdb3 sdb4
*****************************************************.
Machine: Z97P-D3
sdb (250GB_Samsung_SSD_850__Samsung_SSD_850_EVO_250GB_S2MRNX0J205570B)
sdb1 (500M_vfat_NO_NAME(In_Samsung_SSD_850_)_Samsung_SSD_850_EVO_250GB_S2MRNX0J205570B)
sdb3 (8M_bios_grub(In_Samsung_SSD_850_)_Samsung_SSD_850_EVO_250GB_S2MRNX0J205570B)
sdb4 (145.5G_btrfs(In_Samsung_SSD_850_)_Samsung_SSD_850_EVO_250GB_S2MRNX0J205570B)
*****************************************************.
-> "/home/partimag/2020-07-08-15-img".
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
Saving block devices info in /home/partimag/2020-07-08-15-img/blkdev.list...
Saving block devices attributes in /home/partimag/2020-07-08-15-img/blkid.list...
Checking the integrity of partition table in the disk /dev/sdb... 
Reading the partition table for /dev/sdb...RETVAL=0
*****************************************************.
Saving the primary GPT of sdb as /home/partimag/2020-07-08-15-img/sdb-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.000482482 s, 36.1 MB/s
*****************************************************.
Saving the secondary GPT of sdb as /home/partimag/2020-07-08-15-img/sdb-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.000506148 s, 32.4 MB/s
*****************************************************.
Saving the GPT of sdb as /home/partimag/2020-07-08-15-img/sdb-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Saving the MBR data for sdb...
1+0 Datensätze ein
1+0 Datensätze aus
512 Bytes kopiert, 0,000250197 s, 2,0 MB/s
Starting saving /dev/sdb1 as /home/partimag/2020-07-08-15-img/sdb1.XXX...
/dev/sdb1 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will be split with size limit 4096 MB.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Run partclone: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb1 --output - | pigz -c --fast -b 1024 --rsyncable | split -a 2 -b 4096MB - /home/partimag/2020-07-08-15-img/sdb1.vfat-ptcl-img.gz. 2> /tmp/split_error.G9Rbmh
Partclone v0.3.14 http://partclone.org
Starting to clone device (/dev/sdb1) to image (-)
Reading Super Block
memory needed: 21099524 bytes
bitmap 128000 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT16
Device size:  524.3 MB = 1024000 Blocks
Space in use:   5.6 MB = 10912 Blocks
Free Space:   518.7 MB = 1013088 Blocks
Block size:   512 Byte
Total block 1024000
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb1) to the image (-)
>>> Time elapsed: 7.22 secs (~ .120 mins)
*****************************************************.
Finished saving /dev/sdb1 as /home/partimag/2020-07-08-15-img/sdb1.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/sdb3 as /home/partimag/2020-07-08-15-img/sdb3.XXX...
/dev/sdb3 filesystem: bios_grub.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will be split with size limit 4096 MB.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Run partclone: partclone.dd -z 10485760 -N --buffer_size 16777216 -L /var/log/partclone.log -s /dev/sdb3 --output - | pigz -c --fast -b 1024 --rsyncable | split -a 2 -b 4096MB - /home/partimag/2020-07-08-15-img/sdb3.dd-ptcl-img.gz. 2> /tmp/split_error.S273ke
Partclone v0.3.14 http://partclone.org
Starting to clone/restore (/dev/sdb3) to (-) with dd mode
get device size 8388608 by ioctl BLKGETSIZE64,
memory needed: 33556480 bytes
bitmap 2048 bytes, blocks 2*16777216 bytes, checksum 0 bytes
Calculating bitmap... Please wait... done!
File system:  raw
Device size:    8.4 MB = 16384 Blocks
Space in use:   8.4 MB = 16384 Blocks
Free Space:     0 Byte = 0 Blocks
Block size:   512 Byte
Total block 16384
Syncing... OK!
>>> Time elapsed: 6.14 secs (~ .102 mins)
*****************************************************.
Finished saving /dev/sdb3 as /home/partimag/2020-07-08-15-img/sdb3.dd-ptcl-img.gz
*****************************************************.
Starting saving /dev/sdb4 as /home/partimag/2020-07-08-15-img/sdb4.XXX...
/dev/sdb4 filesystem: btrfs.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will be split with size limit 4096 MB.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Run partclone: partclone.btrfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb4 --output - | pigz -c --fast -b 1024 --rsyncable | split -a 2 -b 4096MB - /home/partimag/2020-07-08-15-img/sdb4.btrfs-ptcl-img.gz. 2> /tmp/split_error.3yZsnm
Partclone v0.3.14 http://partclone.org
Starting to clone device (/dev/sdb4) to image (-)
Reading Super Block

btrfsclone.c: btrfs library version = Btrfs v4.2.2
block_size = 16384
usedblock = 5075920
device_size = 156199026688
totalblock = 9533632
btrfsclone.c: fs_close
memory needed: 22163228 bytes
bitmap 1191704 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 

btrfsclone.c: btrfs library version = Btrfs v4.2.2
done!
File system:  BTRFS
Device size:  156.2 GB = 9533632 Blocks
Space in use:  83.2 GB = 5075920 Blocks
Free Space:    73.0 GB = 4457712 Blocks
Block size:   16384 Byte
Total block 9533632
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb4) to the image (-)
>>> Time elapsed: 853.59 secs (~ 14.226 mins)
*****************************************************.
Finished saving /dev/sdb4 as /home/partimag/2020-07-08-15-img/sdb4.btrfs-ptcl-img.gz
*****************************************************.
End of saveparts job for image /home/partimag/2020-07-08-15-img.
*****************************************************.
Saving swap partition sdb5 info in /home/partimag/2020-07-08-15-img/swappt-sdb5.info if it exists...
*****************************************************.
End of savedisk job for image 2020-07-08-15-img.
GPT 1st partition table file found!
GPT 2nd partition table file found!
GPT partition table file for this disk saved by gdisk was found: sdb
MBR file for this disk was found: sdb
[0;39mChecking if udevd rules have to be restored...
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
### End of log ###
### Image created time: 2020-0708-1530
```

Terminal output:

```
[10:12:47 INF] clonezilla-util v2.0.4
[10:12:47 INF] [] [sdb1] Finding optimal decompressor (seekable/sequential)
[10:12:47 INF] [] [sdb1] Loading partition information
[10:12:47 INF] [] [sdb1] Reading partclone content map
[10:12:47 INF] [] [sdb3] Finding optimal decompressor (seekable/sequential)
[10:12:47 INF] [] [sdb3] Loading partition information
[10:12:47 ERR] [] [sdb3] Error while opening partition
System.Exception: Unknown partclone image version: ?↔f?
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
```
