### ISSUE TITLE
Unhandled exception. System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by gnaomo** [fiddyschmitt/clonezilla-util#22]
Hello! Posting the entire log, the program does not like some files in my backed up image i believe...
```
.\clonezilla-util.exe mount -i D:\Backup\PCSpecialist\20221103\2022-11-03-17-img\
[18:18:18 INF] clonezilla-util v2.0.1
[18:18:18 INF] [] [nvme0n1p1] Finding optimal decompressor (seekable/sequential)
[18:18:19 INF] [] [nvme0n1p1] Loading partition information
[18:18:19 ERR] [] [nvme0n1p1] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[18:18:19 INF] [] [nvme0n1p2] Finding optimal decompressor (seekable/sequential)
[18:18:31 INF] [] [nvme0n1p2] Loading partition information
[18:18:32 INF] [] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[18:18:32 INF] [] [nvme0n1p3] Loading partition information
[18:18:32 INF] [] [nvme1n1p1] Finding optimal decompressor (seekable/sequential)
[18:18:32 INF] [] [nvme1n1p1] Loading partition information
[18:18:32 INF] [] [nvme1n1p2] Finding optimal decompressor (seekable/sequential)
[18:18:46 INF] [] [nvme1n1p2] Loading partition information
[18:18:47 INF] Waiting for Z:\ to be available.
[18:18:48 INF] [] [nvme0n1p2] Retrieving a list of files.
[18:20:58 INF] [] [nvme0n1p2] 7zFM.exe will be used to extract files from this partition.
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Users\enric\Documents\Kutools for Outlook\AutoText\Symbol\_
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 , Func`2 , Func`2 , IEqualityComparer`1 )
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 , Func`2 , Func`2 )
   at libClonezilla.Partitions.MountedPartitionImage.CreateTree(String containerName, String partitionName, List`1 allEntries, IExtractor extractor)
   at libClonezilla.Partitions.MountedPartitionImage.GetTree()
   at libClonezilla.Partitions.MountedPartitionImage..ctor(Partition partition, Folder partitionFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Partitions.MountedContainer.<>c__DisplayClass0_0.<.ctor>b__0(Partition partition)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Partitions.MountedContainer..ctor(PartitionContainer container, Folder containerFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Utility.<>c__DisplayClass1_0.<PopulateVFS>b__1(PartitionContainer container)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Utility.PopulateVFS(IVFS vfs, Folder containersRoot, List`1 containers, DesiredContent desiredContent)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

**Comment by fiddyschmitt** [comment]
Thanks for reporting this G!

I'll make a new version which handles that problem.

Could you please post the contents of your `clonezilla-img` file?

**Comment by gnaomo** [comment]
Sure! Here's the cloenzilla-img: https://pastebin.com/tu918qGj

**Comment by fiddyschmitt** [comment]
Hi G,

I've uploaded [version 2.0.2](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v2.0.2), which should address the `item with the same key has already been added` issue you experienced.

Could you please give it a try?

Thanks!
Fidel

**Comment by gnaomo** [comment]
Great! I'm going to try it Monday, thank you!

**Comment by fiddyschmitt** [comment]
No worries! Thanks G!

**Comment by gnaomo** [comment]
Very good! Clonezilla-util got through that error thanks! But now i'm having a different one, closing this issue and opening another one
