### ISSUE TITLE
"Could not find file" Error when extracting with 7zFM

### ISSUE THREAD

**Issue by gnaomo** [fiddyschmitt/clonezilla-util#24]
Log from terminal

```
[22:23:24 INF] clonezilla-util v2.0.2
[22:23:25 INF] [] [nvme0n1p1] Finding optimal decompressor (seekable/sequential)
[22:23:25 INF] [] [nvme0n1p1] Loading partition information
[22:23:25 ERR] [] [nvme0n1p1] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[22:23:25 INF] [] [nvme0n1p2] Finding optimal decompressor (seekable/sequential)
[22:23:40 INF] [] [nvme0n1p2] Loading partition information
[22:23:42 INF] [] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[22:23:42 INF] [] [nvme0n1p3] Loading partition information
[22:23:42 INF] [] [nvme1n1p1] Finding optimal decompressor (seekable/sequential)
[22:23:42 INF] [] [nvme1n1p1] Loading partition information
[22:23:42 INF] [] [nvme1n1p2] Finding optimal decompressor (seekable/sequential)
[22:23:55 INF] [] [nvme1n1p2] Loading partition information
[22:23:58 INF] Waiting for Z:\ to be available.
[22:23:58 INF] [] [nvme0n1p2] Retrieving a list of files.
[22:26:02 INF] [] [nvme0n1p2] 7zFM.exe will be used to extract files from this partition.
[22:28:25 ERR] Could not find Users\enric\Desktop\Reconstructed labeled\Documents\ttf\_____Z__________ in System.Collections.Generic.Dictionary`2[System.String,libDokan.VFS.Folders.Folder]
[22:28:57 INF] [] [nvme0n1p3] Retrieving a list of files.
Unhandled exception. System.Exception: C:\Users\Enrico Dal Bello\Documents\Clonezilla\ext\7-Zip\win-x64\7z.exe l "Z:\a3ec75c2-71cd-47d9-b1f2-9f3a260db1b1 - Temp\3724ef4f-6ca8-4043-ac80-2dd92a0a95fa\nvme0n1p3.img"
Process encountered errors:
ERROR: Z:\a3ec75c2-71cd-47d9-b1f2-9f3a260db1b1 - Temp\3724ef4f-6ca8-4043-ac80-2dd92a0a95fa\nvme0n1p3.img : Cannot open the file as archive


   at libCommon.ProcessUtility.RunCommand(String cpath, String args, Boolean verbose, Boolean throwExceptionIfProcessHadErrors, Func`2 shouldStop)+MoveNext()
   at lib7Zip.SevenZipUtility.IsArchive(String filename)
   at libClonezilla.Partitions.MountedPartitionImage.GetTree()
   at libClonezilla.Partitions.MountedPartitionImage..ctor(Partition partition, Folder partitionFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Partitions.MountedContainer.<>c__DisplayClass0_0.<.ctor>b__0(Partition partition)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Partitions.MountedContainer..ctor(PartitionContainer container, Folder containerFolder, IVFS vfs, DesiredContent desiredContent)
   at libClonezilla.Utility.<>c__DisplayClass1_0.<PopulateVFS>b__1(PartitionContainer container)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.Utility.PopulateVFS(IVFS vfs, Folder containersRoot, List`1 containers, DesiredContent desiredContent)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

My clonezilla-img file:
```
This image was saved by Clonezilla at 2022-11-03 20:10:48 UTC.
Saved by clonezilla-live-3.0.1-8-amd64.
The log during saving:
----------------------------------------------------------
Starting /usr/sbin/ocs-sr at 2022-11-03 17:56:39 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: nvme0n1 nvme1n1
PS. Next time you can run this command directly:
/usr/sbin/ocs-sr -q2 -c -j2 -z1p -i 0 -sfsck -senc -p reboot savedisk 2022-11-03-17-img nvme0n1 nvme1n1
*****************************************************.
The selected devices: nvme0n1 nvme1n1
Searching for data/swap/extended partition(s)...
Searching for data/swap/extended partition(s)...
The data partition to be saved: nvme0n1p1 nvme0n1p2 nvme0n1p3 nvme1n1p1 nvme1n1p2
The selected devices: nvme0n1p1 nvme0n1p2 nvme0n1p3 nvme1n1p1 nvme1n1p2
The following step is to save the hard disk/partition(s) on this machine as an image:
*****************************************************.
Machine: NH50_70RH 
nvme0n1 (500GB_Samsung_SSD_970_EVO_Plus_500GB__Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme1n1 (500GB_Samsung_SSD_970_EVO_Plus_500GB__Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
nvme0n1p1 (16M_MS_Reserved_Partition(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme0n1p2 (465.6G_ntfs(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme0n1p3 (100M_vfat(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme1n1p1 (300M_vfat_NO_LABEL(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
nvme1n1p2 (465.5G_ext4(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
*****************************************************.
-> "/home/partimag/2022-11-03-17-img".
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
Starting saving /dev/nvme0n1p1 as /home/partimag/2022-11-03-17-img/nvme0n1p1.XXX...
/dev/nvme0n1p1 filesystem: MS_Reserved_Partition.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.dd -z 10485760 -N --buffer_size 16777216 -L /var/log/partclone.log -s /dev/nvme0n1p1 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p1.dd-ptcl-img.gz 2> /tmp/img_out_err.acY70A
Partclone v0.3.20 http://partclone.org
Starting to clone/restore (/dev/nvme0n1p1) to (-) with dd mode
get device size 16777216 by ioctl BLKGETSIZE64,
get device size 16777216 by ioctl BLKGETSIZE64,
memory needed: 33558528 bytes
bitmap 4096 bytes, blocks 2*16777216 bytes, checksum 0 bytes
Calculating bitmap... Please wait... done!
File system:  raw
Device size:   16.8 MB = 32768 Blocks
Space in use:  16.8 MB = 32768 Blocks
Free Space:     0 Byte = 0 Blocks
Block size:   512 Byte
Total block 32768
Syncing... OK!
>>> Time elapsed: 6.10 secs (~ .101 mins)
*****************************************************.
Finished saving /dev/nvme0n1p1 as /home/partimag/2022-11-03-17-img/nvme0n1p1.dd-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme0n1p2 as /home/partimag/2022-11-03-17-img/nvme0n1p2.XXX...
/dev/nvme0n1p2 filesystem: ntfs.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ntfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme0n1p2 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p2.ntfs-ptcl-img.gz 2> /tmp/img_out_err.jIVKEb
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme0n1p2) to image (-)
Reading Super Block
memory needed: 36229860 bytes
bitmap 15258336 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  NTFS
Device size:  500.0 GB = 122066687 Blocks
Space in use: 477.8 GB = 116649371 Blocks
Free Space:    22.2 GB = 5417316 Blocks
Block size:   4096 Byte
Total block 122066687
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme0n1p2) to the image (-)
>>> Time elapsed: 4656.41 secs (~ 77.606 mins)
*****************************************************.
Finished saving /dev/nvme0n1p2 as /home/partimag/2022-11-03-17-img/nvme0n1p2.ntfs-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme0n1p3 as /home/partimag/2022-11-03-17-img/nvme0n1p3.XXX...
/dev/nvme0n1p3 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme0n1p3 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p3.vfat-ptcl-img.gz 2> /tmp/img_out_err.0FVgCK
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme0n1p3) to image (-)
Reading Super Block
memory needed: 20997124 bytes
bitmap 25600 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT32
Device size:  104.9 MB = 204800 Blocks
Space in use:  34.6 MB = 67486 Blocks
Free Space:    70.3 MB = 137314 Blocks
Block size:   512 Byte
Total block 204800
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme0n1p3) to the image (-)
>>> Time elapsed: 7.21 secs (~ .120 mins)
*****************************************************.
Finished saving /dev/nvme0n1p3 as /home/partimag/2022-11-03-17-img/nvme0n1p3.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme1n1p1 as /home/partimag/2022-11-03-17-img/nvme1n1p1.XXX...
/dev/nvme1n1p1 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme1n1p1 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme1n1p1.vfat-ptcl-img.gz 2> /tmp/img_out_err.g7PYGh
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme1n1p1) to image (-)
Reading Super Block
memory needed: 21048324 bytes
bitmap 76800 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT32
Device size:  314.6 MB = 614400 Blocks
Space in use:   6.1 MB = 11968 Blocks
Free Space:   308.4 MB = 602432 Blocks
Block size:   512 Byte
Total block 614400
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme1n1p1) to the image (-)
>>> Time elapsed: 7.14 secs (~ .119 mins)
*****************************************************.
Finished saving /dev/nvme1n1p1 as /home/partimag/2022-11-03-17-img/nvme1n1p1.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme1n1p2 as /home/partimag/2022-11-03-17-img/nvme1n1p2.XXX...
/dev/nvme1n1p2 filesystem: ext4.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ext4 -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme1n1p2 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme1n1p2.ext4-ptcl-img.gz 2> /tmp/img_out_err.kAMm9z
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme1n1p2) to image (-)
Reading Super Block
memory needed: 36223861 bytes
bitmap 15252337 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  EXTFS
Device size:  499.8 GB = 122018696 Blocks
Space in use: 351.2 GB = 85752530 Blocks
Free Space:   148.5 GB = 36266166 Blocks
Block size:   4096 Byte
Total block 122018696
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme1n1p2) to the image (-)
>>> Time elapsed: 3142.51 secs (~ 52.375 mins)
*****************************************************.
Finished saving /dev/nvme1n1p2 as /home/partimag/2022-11-03-17-img/nvme1n1p2.ext4-ptcl-img.gz
*****************************************************.
Saving block devices info in /home/partimag/2022-11-03-17-img/blkdev.list...
Saving block devices attributes in /home/partimag/2022-11-03-17-img/blkid.list...
Checking the integrity of partition table in the disk /dev/nvme0n1... 
Reading the partition table for /dev/nvme0n1...RETVAL=0
*****************************************************.
Saving the primary GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00107378 s, 16.2 MB/s
*****************************************************.
Saving the secondary GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00129638 s, 12.6 MB/s
*****************************************************.
Saving the GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Checking the integrity of partition table in the disk /dev/nvme1n1... 
Reading the partition table for /dev/nvme1n1...RETVAL=0
*****************************************************.
Saving the primary GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00242391 s, 7.2 MB/s
*****************************************************.
Saving the secondary GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00250619 s, 6.5 MB/s
*****************************************************.
Saving the GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Saving the MBR data for nvme0n1...
1+0 records in
1+0 records out
512 bytes copied, 0.00314052 s, 163 kB/s
Saving the MBR data for nvme1n1...
1+0 records in
1+0 records out
512 bytes copied, 0.000426941 s, 1.2 MB/s
End of saveparts job for image /home/partimag/2022-11-03-17-img.
*****************************************************.
*****************************************************.
End of savedisk job for image 2022-11-03-17-img.
Checking if udevd rules have to be restored...
This program is not started by Clonezilla server, so skip notifying it the job is done.
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
Finished!
### End of log ###
### Image created time: 2022-1103-2010

```

**Comment by fiddyschmitt** [comment]
Thanks for reporting this G, and double thanks for posting `clonezilla-img` :-)

I've just uploaded [version 2.0.3](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v2.0.3), which displays an error instead of crashing the program.

You still won't see anything for `nvme0n1p1` which is a 16 MB reserved partition, and `nvme0n1p3` which is a 100 MB VFAT partition, because Clonezilla packs them in a different way that I don't yet handle. But hopefully that's okay because usually people aren't interested in extracting files from them.

Please let me know if the new version works for you.
Thanks again for helping make the program better :)

Cheers,
Fidel

**Comment by gnaomo** [comment]
It works!! i've tried this version and the program successfully reaches the "Mounting complete" message, ignoring all of the error messagges.

It's not over yet ahah, there's another error yayy (I may be a magnet for errors)
I'll se you in another issue!

Thank you for everything so far
