### ISSUE TITLE
Access Denied and Unknown partclone image

### ISSUE THREAD

**Issue by NeoPlayer13** [fiddyschmitt/clonezilla-util#26]
First Try
```
F:\clonezilla-util.v2.0.3.win-x64>clonezilla-util.exe mount --input <F:\Win10-2022> --mount L:\ Access is denied.
```
Second try #8 
> In the meantime, the following command may work for you:
clonezilla-util.exe mount --input "D:\2022-08-12-17-manjaro" -m L:\
```
F:\clonezilla-util.v2.0.3.win-x64>clonezilla-util.exe mount --input "F:\Win10-2022" --mount L:\ 
```
```F:\clonezilla-util.v2.0.3.win-x64>clonezilla-util.exe mount --input "F:\Win10-2022" --mount L:\
[05:55:04 INF] clonezilla-util v2.0.3
[05:55:04 INF] [Win10-2022] [sdb1] Finding optimal decompressor (seekable/sequential)
[05:55:04 INF] [Win10-2022] [sdb1] Loading partition information
[05:55:04 ERR] [Win10-2022] [sdb1] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
Unhandled exception. System.Exception: Could not determine compression used by partition stored in F:\Win10-2022\sdb2.ntfs-ptcl-img
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String filename)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

clonezilla-img
```
This image was saved by Clonezilla at 2022-11-14 07:40:14 UTC.
Saved by clonezilla-live-3.0.2-21-amd64.
The log during saving:
----------------------------------------------------------
Starting /usr/sbin/ocs-sr at 2022-11-14 07:10:16 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: sdb
PS. Next time you can run this command directly:
/usr/sbin/ocs-sr -q2 -c -j2 -z9p -i 0 -sfsck -senc -p choose savedisk Win10-2022-11-14-07-img sdb
*****************************************************.
The selected devices: sdb
Searching for data/swap/extended partition(s)...
The data partition to be saved: sdb1 sdb2 sdb3
The selected devices: sdb1 sdb2 sdb3
The following step is to save the hard disk/partition(s) on this machine as an image:
*****************************************************.
Machine: System Product Name
sdb (512GB_Samsung_SSD_850__Samsung_SSD_850_PRO_512GB_S250NXAH219628W)
sdb1 (16M_MS_Reserved_Partition(In_Samsung_SSD_850_)_Samsung_SSD_850_PRO_512GB_S250NXAH219628W)
sdb2 (428.7G_ntfs_OS_Win_10(In_Samsung_SSD_850_)_Samsung_SSD_850_PRO_512GB_S250NXAH219628W)
sdb3 (540M_ntfs(In_Samsung_SSD_850_)_Samsung_SSD_850_PRO_512GB_S250NXAH219628W)
*****************************************************.
-> "/home/partimag/Win10-2022-11-14-07-img".
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
Starting saving /dev/sdb1 as /home/partimag/Win10-2022-11-14-07-img/sdb1.XXX...
/dev/sdb1 filesystem: MS_Reserved_Partition.
*****************************************************.
*****************************************************.
Use partclone with zstdmt to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.dd -z 10485760 -N --buffer_size 16777216 -L /var/log/partclone.log -s /dev/sdb1 --output - | zstdmt -c -3 > /home/partimag/Win10-2022-11-14-07-img/sdb1.dd-ptcl-img.zst 2> /tmp/img_out_err.yBXhVd
Partclone v0.3.20 http://partclone.org
Starting to clone/restore (/dev/sdb1) to (-) with dd mode
get device size 16777216 by ioctl BLKGETSIZE64,
get device size 16777216 by ioctl BLKGETSIZE64,
memory needed: 33558528 bytes
bitmap 4096 bytes, blocks 2*16777216 bytes, checksum 0 bytes
Calculating bitmap... Please wait... done!
File system:  raw
Device size:   16.8 MB = 32768 Blocks
Space in use:  16.8 MB = 32768 Blocks
Free Space:     0 Byte = 0 Blocks
Block size:   512 Byte
Total block 32768
Syncing... OK!
>>> Time elapsed: 6.22 secs (~ .103 mins)
*****************************************************.
Finished saving /dev/sdb1 as /home/partimag/Win10-2022-11-14-07-img/sdb1.dd-ptcl-img.zst
*****************************************************.
Starting saving /dev/sdb2 as /home/partimag/Win10-2022-11-14-07-img/sdb2.XXX...
/dev/sdb2 filesystem: ntfs.
*****************************************************.
*****************************************************.
Use partclone with zstdmt to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ntfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb2 --output - | zstdmt -c -3 > /home/partimag/Win10-2022-11-14-07-img/sdb2.ntfs-ptcl-img.zst 2> /tmp/img_out_err.XcMm7v
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/sdb2) to image (-)
Reading Super Block
memory needed: 35019151 bytes
bitmap 14047627 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  NTFS
Device size:  460.3 GB = 112381009 Blocks
Space in use: 185.5 GB = 45295483 Blocks
Free Space:   274.8 GB = 67085526 Blocks
Block size:   4096 Byte
Total block 112381009
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb2) to the image (-)
>>> Time elapsed: 1624.73 secs (~ 27.078 mins)
*****************************************************.
Finished saving /dev/sdb2 as /home/partimag/Win10-2022-11-14-07-img/sdb2.ntfs-ptcl-img.zst
*****************************************************.
Starting saving /dev/sdb3 as /home/partimag/Win10-2022-11-14-07-img/sdb3.XXX...
/dev/sdb3 filesystem: ntfs.
*****************************************************.
*****************************************************.
Use partclone with zstdmt to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ntfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/sdb3 --output - | zstdmt -c -3 > /home/partimag/Win10-2022-11-14-07-img/sdb3.ntfs-ptcl-img.zst 2> /tmp/img_out_err.AUlX4U
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/sdb3) to image (-)
Reading Super Block
memory needed: 20988804 bytes
bitmap 17280 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  NTFS
Device size:  566.2 MB = 138239 Blocks
Space in use: 500.8 MB = 122268 Blocks
Free Space:    65.4 MB = 15971 Blocks
Block size:   4096 Byte
Total block 138239
Syncing... OK!
Partclone successfully cloned the device (/dev/sdb3) to the image (-)
>>> Time elapsed: 13.28 secs (~ .221 mins)
*****************************************************.
Finished saving /dev/sdb3 as /home/partimag/Win10-2022-11-14-07-img/sdb3.ntfs-ptcl-img.zst
*****************************************************.
Dumping the device mapper table in /home/partimag/Win10-2022-11-14-07-img/dmraid.table...
Saving block devices info in /home/partimag/Win10-2022-11-14-07-img/blkdev.list...
Saving block devices attributes in /home/partimag/Win10-2022-11-14-07-img/blkid.list...
Checking the integrity of partition table in the disk /dev/sdb... 
Reading the partition table for /dev/sdb...RETVAL=0
*****************************************************.
Saving the primary GPT of sdb as /home/partimag/Win10-2022-11-14-07-img/sdb-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00175369 s, 9.9 MB/s
*****************************************************.
Saving the secondary GPT of sdb as /home/partimag/Win10-2022-11-14-07-img/sdb-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00138684 s, 11.8 MB/s
*****************************************************.
Saving the GPT of sdb as /home/partimag/Win10-2022-11-14-07-img/sdb-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Saving the MBR data for sdb...
1+0 records in
1+0 records out
512 bytes copied, 0.000490304 s, 1.0 MB/s
End of saveparts job for image /home/partimag/Win10-2022-11-14-07-img.
*****************************************************.
*****************************************************.
End of savedisk job for image Win10-2022-11-14-07-img.
Checking if udevd rules have to be restored...
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
### End of log ###
### Image created time: 2022-1114-0740
```

**Comment by fiddyschmitt** [comment]
Thanks for reporting it Neo,

`sdb1` is just a 16 MB reserved partition. Despite the error, the program should have continued. Do you see your files in `L:\sdb2`?

**Comment by NeoPlayer13** [comment]
No, it does not mount the `sdb2`, the error stops the program from continuing.

**Comment by fiddyschmitt** [comment]
I see. Perhaps try specifying the partition using the following:

`clonezilla-util.exe mount --input "F:\Win10-2022" --mount L:\ -p sdb2`

**Comment by NeoPlayer13** [comment]
```
F:\clonezilla-util.v2.0.3.win-x64>clonezilla-util.exe mount --input "F:\Win10-2022" --mount L:\ -p sdb2
[05:51:48 INF] clonezilla-util v2.0.3
Unhandled exception. System.Exception: Could not determine compression used by partition stored in F:\Win10-2022\sdb2.ntfs-ptcl-img
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String filename)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

**Comment by fiddyschmitt** [comment]
Thanks Neo, could you please try renaming `sdb2.ntfs-ptcl-img` to `sdb2.ntfs-ptcl-img.zst`?

**Comment by NeoPlayer13** [comment]
It was already named `sdb2.ntfs-ptcl-img.zst`, but your suggestion gave me an idea. I was working with a copy because I didn't want to corrupt the original backup folder, made a new copy from the original in Windows, and it worked perfectly.
The first copy was made in a Arch based distro, don't know if there was some sort of error while copying the files or when I was trying to extract the zst files with `unzstd` and `zstdcat`.

Thanks a lot man, you saved me from hours of extra work.

**Comment by fiddyschmitt** [comment]
:D that's great! Thanks Neo
