### ISSUE TITLE
System ERROR: A device attached to the system is not functioning.

### ISSUE THREAD

**Issue by gnaomo** [fiddyschmitt/clonezilla-util#27]
### clonezilla-img:
```
This image was saved by Clonezilla at 2022-11-03 20:10:48 UTC.
Saved by clonezilla-live-3.0.1-8-amd64.
The log during saving:
----------------------------------------------------------
Starting /usr/sbin/ocs-sr at 2022-11-03 17:56:39 UTC...
*****************************************************.
Clonezilla image dir: /home/partimag
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
The selected devices: nvme0n1 nvme1n1
PS. Next time you can run this command directly:
/usr/sbin/ocs-sr -q2 -c -j2 -z1p -i 0 -sfsck -senc -p reboot savedisk 2022-11-03-17-img nvme0n1 nvme1n1
*****************************************************.
The selected devices: nvme0n1 nvme1n1
Searching for data/swap/extended partition(s)...
Searching for data/swap/extended partition(s)...
The data partition to be saved: nvme0n1p1 nvme0n1p2 nvme0n1p3 nvme1n1p1 nvme1n1p2
The selected devices: nvme0n1p1 nvme0n1p2 nvme0n1p3 nvme1n1p1 nvme1n1p2
The following step is to save the hard disk/partition(s) on this machine as an image:
*****************************************************.
Machine: NH50_70RH 
nvme0n1 (500GB_Samsung_SSD_970_EVO_Plus_500GB__Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme1n1 (500GB_Samsung_SSD_970_EVO_Plus_500GB__Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
nvme0n1p1 (16M_MS_Reserved_Partition(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme0n1p2 (465.6G_ntfs(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme0n1p3 (100M_vfat(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNM0NC08240K)
nvme1n1p1 (300M_vfat_NO_LABEL(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
nvme1n1p2 (465.5G_ext4(In_Samsung_SSD_970_EVO_Plus_500GB_)_Samsung_SSD_970_EVO_Plus_500GB_S4EVNF0M711514V)
*****************************************************.
-> "/home/partimag/2022-11-03-17-img".
Shutting down the Logical Volume Manager
Finished Shutting down the Logical Volume Manager
Starting saving /dev/nvme0n1p1 as /home/partimag/2022-11-03-17-img/nvme0n1p1.XXX...
/dev/nvme0n1p1 filesystem: MS_Reserved_Partition.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.dd -z 10485760 -N --buffer_size 16777216 -L /var/log/partclone.log -s /dev/nvme0n1p1 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p1.dd-ptcl-img.gz 2> /tmp/img_out_err.acY70A
Partclone v0.3.20 http://partclone.org
Starting to clone/restore (/dev/nvme0n1p1) to (-) with dd mode
get device size 16777216 by ioctl BLKGETSIZE64,
get device size 16777216 by ioctl BLKGETSIZE64,
memory needed: 33558528 bytes
bitmap 4096 bytes, blocks 2*16777216 bytes, checksum 0 bytes
Calculating bitmap... Please wait... done!
File system:  raw
Device size:   16.8 MB = 32768 Blocks
Space in use:  16.8 MB = 32768 Blocks
Free Space:     0 Byte = 0 Blocks
Block size:   512 Byte
Total block 32768
Syncing... OK!
>>> Time elapsed: 6.10 secs (~ .101 mins)
*****************************************************.
Finished saving /dev/nvme0n1p1 as /home/partimag/2022-11-03-17-img/nvme0n1p1.dd-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme0n1p2 as /home/partimag/2022-11-03-17-img/nvme0n1p2.XXX...
/dev/nvme0n1p2 filesystem: ntfs.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ntfs -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme0n1p2 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p2.ntfs-ptcl-img.gz 2> /tmp/img_out_err.jIVKEb
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme0n1p2) to image (-)
Reading Super Block
memory needed: 36229860 bytes
bitmap 15258336 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  NTFS
Device size:  500.0 GB = 122066687 Blocks
Space in use: 477.8 GB = 116649371 Blocks
Free Space:    22.2 GB = 5417316 Blocks
Block size:   4096 Byte
Total block 122066687
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme0n1p2) to the image (-)
>>> Time elapsed: 4656.41 secs (~ 77.606 mins)
*****************************************************.
Finished saving /dev/nvme0n1p2 as /home/partimag/2022-11-03-17-img/nvme0n1p2.ntfs-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme0n1p3 as /home/partimag/2022-11-03-17-img/nvme0n1p3.XXX...
/dev/nvme0n1p3 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme0n1p3 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme0n1p3.vfat-ptcl-img.gz 2> /tmp/img_out_err.0FVgCK
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme0n1p3) to image (-)
Reading Super Block
memory needed: 20997124 bytes
bitmap 25600 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT32
Device size:  104.9 MB = 204800 Blocks
Space in use:  34.6 MB = 67486 Blocks
Free Space:    70.3 MB = 137314 Blocks
Block size:   512 Byte
Total block 204800
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme0n1p3) to the image (-)
>>> Time elapsed: 7.21 secs (~ .120 mins)
*****************************************************.
Finished saving /dev/nvme0n1p3 as /home/partimag/2022-11-03-17-img/nvme0n1p3.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme1n1p1 as /home/partimag/2022-11-03-17-img/nvme1n1p1.XXX...
/dev/nvme1n1p1 filesystem: vfat.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.vfat -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme1n1p1 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme1n1p1.vfat-ptcl-img.gz 2> /tmp/img_out_err.g7PYGh
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme1n1p1) to image (-)
Reading Super Block
memory needed: 21048324 bytes
bitmap 76800 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  FAT32
Device size:  314.6 MB = 614400 Blocks
Space in use:   6.1 MB = 11968 Blocks
Free Space:   308.4 MB = 602432 Blocks
Block size:   512 Byte
Total block 614400
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme1n1p1) to the image (-)
>>> Time elapsed: 7.14 secs (~ .119 mins)
*****************************************************.
Finished saving /dev/nvme1n1p1 as /home/partimag/2022-11-03-17-img/nvme1n1p1.vfat-ptcl-img.gz
*****************************************************.
Starting saving /dev/nvme1n1p2 as /home/partimag/2022-11-03-17-img/nvme1n1p2.XXX...
/dev/nvme1n1p2 filesystem: ext4.
*****************************************************.
*****************************************************.
Use partclone with pigz to save the image.
Image file will not be split.
*****************************************************.
If this action fails or hangs, check:
* Is the disk full ?
*****************************************************.
Running: partclone.ext4 -z 10485760 -N -L /var/log/partclone.log -c -s /dev/nvme1n1p2 --output - | pigz -c --fast -b 1024 --rsyncable > /home/partimag/2022-11-03-17-img/nvme1n1p2.ext4-ptcl-img.gz 2> /tmp/img_out_err.kAMm9z
Partclone v0.3.20 http://partclone.org
Starting to clone device (/dev/nvme1n1p2) to image (-)
Reading Super Block
memory needed: 36223861 bytes
bitmap 15252337 bytes, blocks 2*10485760 bytes, checksum 4 bytes
Calculating bitmap... Please wait... 
done!
File system:  EXTFS
Device size:  499.8 GB = 122018696 Blocks
Space in use: 351.2 GB = 85752530 Blocks
Free Space:   148.5 GB = 36266166 Blocks
Block size:   4096 Byte
Total block 122018696
Syncing... OK!
Partclone successfully cloned the device (/dev/nvme1n1p2) to the image (-)
>>> Time elapsed: 3142.51 secs (~ 52.375 mins)
*****************************************************.
Finished saving /dev/nvme1n1p2 as /home/partimag/2022-11-03-17-img/nvme1n1p2.ext4-ptcl-img.gz
*****************************************************.
Saving block devices info in /home/partimag/2022-11-03-17-img/blkdev.list...
Saving block devices attributes in /home/partimag/2022-11-03-17-img/blkid.list...
Checking the integrity of partition table in the disk /dev/nvme0n1... 
Reading the partition table for /dev/nvme0n1...RETVAL=0
*****************************************************.
Saving the primary GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00107378 s, 16.2 MB/s
*****************************************************.
Saving the secondary GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00129638 s, 12.6 MB/s
*****************************************************.
Saving the GPT of nvme0n1 as /home/partimag/2022-11-03-17-img/nvme0n1-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Checking the integrity of partition table in the disk /dev/nvme1n1... 
Reading the partition table for /dev/nvme1n1...RETVAL=0
*****************************************************.
Saving the primary GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt-1st by dd...
34+0 records in
34+0 records out
17408 bytes (17 kB, 17 KiB) copied, 0.00242391 s, 7.2 MB/s
*****************************************************.
Saving the secondary GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt-2nd by dd...
32+0 records in
32+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.00250619 s, 6.5 MB/s
*****************************************************.
Saving the GPT of nvme1n1 as /home/partimag/2022-11-03-17-img/nvme1n1-gpt.gdisk by gdisk...
The operation has completed successfully.
*****************************************************.
Saving the MBR data for nvme0n1...
1+0 records in
1+0 records out
512 bytes copied, 0.00314052 s, 163 kB/s
Saving the MBR data for nvme1n1...
1+0 records in
1+0 records out
512 bytes copied, 0.000426941 s, 1.2 MB/s
End of saveparts job for image /home/partimag/2022-11-03-17-img.
*****************************************************.
*****************************************************.
End of savedisk job for image 2022-11-03-17-img.
Checking if udevd rules have to be restored...
This program is not started by Clonezilla server, so skip notifying it the job is done.
This program is not started by Clonezilla server, so skip notifying it the job is done.
Finished!
Finished!
### End of log ###
### Image created time: 2022-1103-2010

```

### Terminal log:
```
[13:39:08 INF] clonezilla-util v2.0.3
[13:39:09 INF] [] [nvme0n1p1] Finding optimal decompressor (seekable/sequential)
[13:39:09 INF] [] [nvme0n1p1] Loading partition information
[13:39:09 ERR] [] [nvme0n1p1] Error while opening partition
System.Exception: Unknown partclone image version:
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[13:39:09 INF] [] [nvme0n1p2] Finding optimal decompressor (seekable/sequential)
[13:39:23 INF] [] [nvme0n1p2] Loading partition information
[13:39:24 INF] [] [nvme0n1p3] Finding optimal decompressor (seekable/sequential)
[13:39:24 INF] [] [nvme0n1p3] Loading partition information
[13:39:24 INF] [] [nvme1n1p1] Finding optimal decompressor (seekable/sequential)
[13:39:24 INF] [] [nvme1n1p1] Loading partition information
[13:39:24 INF] [] [nvme1n1p2] Finding optimal decompressor (seekable/sequential)
[13:39:35 INF] [] [nvme1n1p2] Loading partition information
[13:39:36 INF] Waiting for Z:\ to be available.
[13:39:37 INF] [] [nvme0n1p2] Retrieving a list of files.
[13:41:30 INF] [] [nvme0n1p2] 7zFM.exe will be used to extract files from this partition.
[13:43:35 ERR] Error while finding parent of __________000149.ttf
[13:43:35 ERR] Could not find Users\enric\Desktop\Reconstructed labeled\Documents\ttf\_____Z__________ in folderLookup
[13:44:03 INF] [] [nvme0n1p3] Retrieving a list of files.
[13:44:04 ERR] C:\Users\Enrico Dal Bello\Documents\Clonezilla\ext\7-Zip\win-x64\7z.exe l "Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\319bffe6-44fe-4e10-9e76-8843979ac616\nvme0n1p3.img"
Process encountered errors:
ERROR: Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\319bffe6-44fe-4e10-9e76-8843979ac616\nvme0n1p3.img : Cannot open the file as archive


[13:44:04 ERR] [] [nvme0n1p3] The image file for this partition (Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\319bffe6-44fe-4e10-9e76-8843979ac616\nvme0n1p3.img) is not considered an archive by 7-Zip. Returning empty file list.
[13:44:04 INF] [] [nvme1n1p1] Retrieving a list of files.
[13:44:04 ERR] C:\Users\Enrico Dal Bello\Documents\Clonezilla\ext\7-Zip\win-x64\7z.exe l "Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\e58d0e55-8cbd-4f43-842b-9468ff3597dc\nvme1n1p1.img"
Process encountered errors:
ERROR: Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\e58d0e55-8cbd-4f43-842b-9468ff3597dc\nvme1n1p1.img : Cannot open the file as archive


[13:44:04 ERR] [] [nvme1n1p1] The image file for this partition (Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\e58d0e55-8cbd-4f43-842b-9468ff3597dc\nvme1n1p1.img) is not considered an archive by 7-Zip. Returning empty file list.
[13:44:04 INF] [] [nvme1n1p2] Retrieving a list of files.
[17:22:23 ERR] C:\Users\Enrico Dal Bello\Documents\Clonezilla\ext\7-Zip\win-x64\7z.exe l "Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img"
Process encountered errors:
ERROR: Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img : opening : A device attached to the system is not functioning.


System ERROR:
A device attached to the system is not functioning.
[17:22:23 ERR] [] [nvme1n1p2] The image file for this partition (Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img) is not considered an archive by 7-Zip. Returning empty file list.
[17:22:23 INF] Mounting complete. Mounted to: Z:\
Running. Press Enter to exit.
```

### This is the crucial part:

```
[...]
[13:44:04 INF] [] [nvme1n1p2] Retrieving a list of files.
[17:22:23 ERR] C:\Users\Enrico Dal Bello\Documents\Clonezilla\ext\7-Zip\win-x64\7z.exe l "Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img"
Process encountered errors:
ERROR: Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img : opening : A device attached to the system is not functioning.


System ERROR:
A device attached to the system is not functioning.
[17:22:23 ERR] [] [nvme1n1p2] The image file for this partition (Z:\a3c6b13e-3a90-42fe-beb5-8cbb3de73880 - Temp\95eb1d56-b1d7-4a16-9d60-5f0e55c2f969\nvme1n1p2.img) is not considered an archive by 7-Zip. Returning empty file list.
[17:22:23 INF] Mounting complete. Mounted to: Z:\
Running. Press Enter to exit.
```

It's the last partition (400gb ext4 nvme1n1p2) which will not get mounted.

Reading this error message at first thought makes me think maybe its related to my external disk (where the clonezilla backup is stored). Maybe the program suddenly stops reading the disk and throws this error (computer falling asleep or external disk somehow disconnects/goes inactive)
I tried to rerun the program another 2 times, deleting the cache folder and making sure the computer never falls asleep (Roughly it's 3 hours and an half) .Always with the same result/error.

What do you think?

> P.S. I don't know if i'm making the right thing always opening another issue for different errors (please let me know if i'm making things too messy!)

**Comment by fiddyschmitt** [comment]
Thanks G!
A new issue for each error is good (and appreciated).

Could you please try extracting `nvme1n1p2` using the following command?
`clonezilla-util.exe extract-partition-image --input <clonzilla folder> --output <folder to extract to> -p nvme1n1p2`

Once extracted, could you please right-click the file, and choose 7-Zip -> Open archive?
Hopefully it will show you a list of files.

**Comment by gnaomo** [comment]
Tried the command and it seems to always get stuck with the extraction at 31.74/465.46 GB (i ran the command twice)

Does that mean that my backed up partition is damaged? :(

**Comment by fiddyschmitt** [comment]
Oh interesting. No, I doubt your backup or partition is damaged - it's much more likely I have a bug in the code.

I'll do some chin-scratching and get back to you.

**Comment by gnaomo** [comment]
Managed to open it successfully! I extracted it on my ssd rather than the same external disk, it took 18 hours but now the archive successfully opens with 7zip (but not with winrar or windows 11 explorer).

Is EXT4 mounting slower/more problematic than NTFS?

**Comment by fiddyschmitt** [comment]
Thanks G, that's great!!
Out of interest - how long does it take to open the extracted EXT4 file with 7-Zip?

It's strange that there's such a difference between EXT4 and NTFS, as the program treats both the same (ie. unpack gz, unpack partclone, and pass the file to 7-Zip).

**Comment by fiddyschmitt** [comment]
If able, could you please run your _mount_ command again, but this time using the program linked below? It uses a different way to cache the gz, which might prevent the 'Device not functioning' error.
Thanks!

[clonezilla-util.v2.0.3g.win-x64.zip](https://github.com/fiddyschmitt/clonezilla-util/files/10045478/clonezilla-util.v2.0.3g.win-x64.zip)

**Comment by gnaomo** [comment]
> Out of interest - how long does it take to open the extracted EXT4 file with 7-Zip?

I would say 20 to 30 seconds.

![ezgif-2-b6b9857023](https://user-images.githubusercontent.com/38522864/202825413-97c4289e-7392-478b-8136-01bb44586842.gif)




> clonezilla-util.v2.0.3g.win-x64.zip

Thank you! I'm going to try it and let you know

**Comment by fiddyschmitt** [comment]
:D an animated gif... so good!
Thanks!

**Comment by gnaomo** [comment]
Update!

At 200 GB of caching, the program stops cause there is no space free left on my 500GB ssd, if i target only the EXT4 partition and make the program build 465GB of cache on another 500GB empty ssd i might be able to do it. How do i mount a specific partition?

I assume that, as a path, instead of a folder you just input your desired .gz compressed image:

![image](https://user-images.githubusercontent.com/38522864/202854263-4489525f-44d9-431a-92ed-eb1c5a0ed597.png)

**Comment by fiddyschmitt** [comment]
Thanks!

Please still specify the _folder_, and use an extra argument: `-p nvme1n1p2`

**Comment by gnaomo** [comment]
```
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] [] [nvme1n1p2] Cached 327.13 GB. (100% through source file)
[21:54:47 INF] Successfully cached to: D:\different caching system\cache\7edde6b93d37a41b0afc610d5b52bda0\cache.train
[21:54:51 INF] [] [nvme1n1p2] Loading partition information
[21:54:51 INF] [] [nvme1n1p2] Reading partclone content map
[21:54:56 INF] Waiting for Z:\ to be available.
[21:54:56 INF] [] [nvme1n1p2] Retrieving a list of files.
[22:01:36 ERR] D:\different caching system\ext\7-Zip\win-x64\7z.exe l "Z:\8d5bd4e0-80e4-46ad-b51e-c9b90119d65c - Temp\8bb397b3-9e99-4bd7-88a7-c74e0805ef98\nvme1n1p2.img"
Process encountered errors:
ERROR: Z:\8d5bd4e0-80e4-46ad-b51e-c9b90119d65c - Temp\8bb397b3-9e99-4bd7-88a7-c74e0805ef98\nvme1n1p2.img : opening : A device attached to the system is not functioning.


System ERROR:
A device attached to the system is not functioning.
[22:01:36 ERR] [] [nvme1n1p2] The image file for this partition (Z:\8d5bd4e0-80e4-46ad-b51e-c9b90119d65c - Temp\8bb397b3-9e99-4bd7-88a7-c74e0805ef98\nvme1n1p2.img) is not considered an archive by 7-Zip. Returning empty file list.
[22:01:36 INF] Mounting complete. Mounted to: Z:\
Running. Press Enter to exit.
```

Returned me same error!

**Comment by fiddyschmitt** [comment]
Thanks G! Much appreciated!

I suspect that clonezilla-util is taking too long to provide 7z.exe with data, so 7z.exe concludes there's some device error.

To test that theory, could you please run this command:

`"D:\different caching system\ext\7-Zip\win-x64\7z.exe" l "D:\nvme1n1p2.img"`

It should list the files in that partition, or display the `device not functioning` error.

Thanks!

**Comment by gnaomo** [comment]
No errors!

![image](https://user-images.githubusercontent.com/38522864/202879753-332a55ab-f013-4df7-9e24-5e69294ef745.png)

**Comment by fiddyschmitt** [comment]
Interesting!!
I'll have to look into what causes this.

Please accept my sincere thanks for helping diagnose this. You've definitely gone above and beyond :smile:

**Comment by gnaomo** [comment]
No problem, thank you for the support so far, really like it.
