### ISSUE TITLE
Unhandled exception. System.Exception: Could not determine if this is a Clonezilla folder, or a partclone file

### ISSUE THREAD

**Issue by JohnnyElvis** [fiddyschmitt/clonezilla-util#32]
Hi, I'm new to the clonezilla-util, problem might be between chair and keyboard....but this is what is happening to me:

I have a image separated into 5 gz files to fit FAT32 file systems and hash file included.

my_image.gz.aa
my_image.gz.ab
my_image.gz.ac
my_image.gz.ad
my_image.gz.ae
my_image.hash.txt

When I try to mount the image via "clonezilla-util.exe mount-as-image-files --input C:\Temp\my_image\ --mount L:\"

I get following error message:

[11:23:32 INF] clonezilla-util v2.0.4
Unhandled exception. System.Exception: Could not determine if this is a Clonezilla folder, or a partclone file: C:\Temp\my_image\
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsImageFiles(MountAsImageFiles mountAsImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

So far so good I thought, let's extract the image first. Well, only a single archive of those 5 get's extracted when I execute clonezilla-util.exe extract-partition-image --input C:\Temp\my_image\my_image.gz.aa --output C:\Temp\my_image\extracted

Am I doing something wrong? Or is there an issue with this use case?

BR & Thx

**Comment by fiddyschmitt** [comment]
Hi Johnny,

Thanks for reporting this. Everything you've tried is logical :)

Could you please upload the file called `clonezilla-img`?

Thanks!
Fidel
