### ISSUE TITLE
Impossible to open encrypted partition

### ISSUE THREAD

**Issue by harryssecret** [fiddyschmitt/clonezilla-util#33]
Hey ! I've tried using your tool to open a encrypted partition i just made with clonezilla (from a ext4 drive) and i chose to encrypt it. However, clonezilla-util is crashing, and give me the following error : 
```
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 , Func`2 )
   at libClonezilla.Cache.ClonezillaCacheManager.GetPartitionCache(String partitionName)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.ExtractPartitionImage(ExtractPartitionImage extractPartitionImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

thanks for the help:)
Here is the command i ran to get this result : `.\clonezilla-util.exe extract-partition-image --input E:\Sauvegardes\2023-04-19-08-img\ --output D:\fichiers`
Is my image corrupted, or does the software not support encrypted parts?

**Comment by fiddyschmitt** [comment]
Hi Harry!
Encrypted images aren't supported yet. I'll have to study how they are packaged, and update the program.

Cheers,
Fidel

**Comment by dyehya** [comment]
Hey @fiddyschmitt, any updates on this? Just ran into this issue. Also, if it will take time, it might be great if you can update the error so at least the user knows why this is happening. Then again, it is open source and free so I guess I can't ask for a refund. ;) But seriously appreciate the work you put into this and while I can't use it for the specific one I am trying to access, it will be very helpful for another one!
