### ISSUE TITLE
Unhandled exception. System.Exception: File not found: clonezilla

### ISSUE THREAD

**Issue by djsomi** [fiddyschmitt/clonezilla-util#43]
Hi Everyone,

I've tried to use the latest clonezilla-util.v2.0.4.win-x64 tool, and dropping this error on Win11:

`Unhandled exception. System.Exception: File not found: clonezilla
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List1 paths, String cacheFolder, List1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsImageFiles(MountAsImageFiles mountAsImageOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult1 result, Action1 action)
   at clonezilla_util.Program.Main(String[] args)`

Any suggestion what to check?

Many thanks!

**Comment by fiddyschmitt** [comment]
Hi Somi!

Happy to help. Could you please post the command you're running?

Thanks,
Fidel

**Comment by djsomi** [comment]
Sorry my bad, accidentally i left "clonezilla image" word before --mount! Working fine now!
