### ISSUE TITLE
Trailing backslash in the "--input" argument breaks things

### ISSUE THREAD

**Issue by i3v** [fiddyschmitt/clonezilla-util#48]
I've just noticed that the trailing backslash breaks things:

```
C:\temp>clonezilla-util.exe mount --input "d:\Clonezilla\2023-11-09-08_img\" --mount L:\
[22:08:30 INF] clonezilla-util v2.0.4
Unhandled exception. System.Exception: File not found: d:\Clonezilla\2023-11-09-08_img" --mount L:\
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```
Same thing with no trailing backslash perfectly works:
```
C:\temp>clonezilla-util.exe mount --input "d:\Clonezilla\2023-11-09-08_img" --mount L:\
[22:11:00 INF] clonezilla-util v2.0.4
[22:11:06 INF] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb1] Finding optimal decompressor (seekable/sequential)
[22:11:18 INF] Generating gzip index.
```
Release 2.0.4 version.

I'd expect that both versions would work.

**Comment by fiddyschmitt** [comment]
Thanks Igor,

Yes unfortunately this is standard Windows behaviour where using a backslash means 'escape the next character'.
