### ISSUE TITLE
List of supported/unsupported Clonezilla image types?

### ISSUE THREAD

**Issue by i3v** [fiddyschmitt/clonezilla-util#49]
It looks like clonezilla-util is unable to mount the image I created, because I used `Only dd` option and clonezilla-util  requires `partclone`.  
```
[23:25:12 INF] Indexed 237.1 GB / 237.1 GB (100%)
[23:25:12 INF] Indexed 237.1 GB / 237.1 GB (100%)
Index written to 'C:\Program Files\clonezilla-image-mount-util\cache\3aa834abbde88eac\sdb2.gztool_index.gzi.wip'.
Built index with 45354 access points.


[23:25:12 INF] Finished generating gzip index. Moving to final location: C:\Program Files\clonezilla-image-mount-util\cache\3aa834abbde88eac\sdb2.gztool_index.gzi
[23:25:15 INF] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb2] Loading partition information
[23:25:16 ERR] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb2] Error while opening partition
System.Exception: Unknown partclone image version: ☼
   at libPartclone.PartcloneImageInfo..ctor(String containerName, String partitionName, Stream readStream, IPartcloneCache cache)
   at libPartclone.PartcloneStream..ctor(String containerName, String partitionName, Stream inputStream, IPartcloneCache cache)
   at libClonezilla.Partitions.PartclonePartition..ctor(String originFilename, PartitionContainer container, String partitionName, Stream compressedPartcloneStream, Nullable`1 uncompressedLength, Compression compressionInUse, IPartitionCache partitionCache, IPartcloneCache partcloneCache, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
[23:25:16 INF] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb3] Finding optimal decompressor (seekable/sequential)
[23:25:23 INF] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb3] Loading partition information
[23:25:23 ERR] [2023-11-09-08-IMP_boot_issues_after_RAID1_img] [sdb3] Error while opening partition
```
Am I correct about this?
Is there a more-or-less complete list of supported / unsupported Clonezilla options? Is it only "partclone" that is actually supported? 

Here's the contents of my`Info-saved-by-cmd`:
`
/usr/sbin/ocs-sr -q1 -c -j2 -ntfs-ok -z1p -i 4096 -sfsck -senc -p cmd savedisk finename sdb
`

The `dd` vs `partclone` in the Clonezilla [advanced mode menu](https://clonezilla.org/clonezilla-live/doc/01_Save_disk_image/advanced/09-advanced-param.php), just for reference:
![image](https://github.com/fiddyschmitt/clonezilla-util/assets/920364/f3ab4265-65d4-4918-b933-5f07d32bd64c)

**Comment by fiddyschmitt** [comment]
Thanks for the detailed report Igor! I have a fix which I'm testing now, and I'll release an update tomorrow.

**Comment by fiddyschmitt** [comment]
I've encountered some issues, so it'll be a while longer

**Comment by i3v** [comment]
It's good to know that you assume that this type of images should be supported, at least :)
The ability to get a few files out of the image without unpacking the whole image is quite valuable.

**Comment by fiddyschmitt** [comment]
Hi Igor,

[v2.1.0](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v2.1.0) now supports dd-based Clonezilla images.

Please let me know how it goes.

Cheers!
Fidel

**Comment by i3v** [comment]
I can confirm this works now! 
Thanks a lot!

**Comment by fiddyschmitt** [comment]
Awesome!! Thanks for confirming 😁
