### ISSUE TITLE
Missing compression algorithm (bzip2)

### ISSUE THREAD

**Issue by kerstin921** [fiddyschmitt/clonezilla-util#5]
Hi,

I'm getting an unknown compression error:

```
F:\>clonezilla-util.exe mount --input ./a --mount L:
[03:15:21 INF] clonezilla-util v1.5.3
Unhandled exception. System.Exception: Could not determine compression used by p
artition sda1 in: ./a
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(Stri
ng clonezillaArchiveFolder, String partitionName)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.c
tor>b__2(String partitionName)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaA
rchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boo
lean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path,
 String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking,
IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.
<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 path
s, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking
, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Ac
tion`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

The image was created using the command (as stored in the Clonezilla _Info-saved-by-cmd.txt_ file)

`/usr/sbin/ocs-sr -q2 -c -j2 -rm-win-swap-hib -ntfs-ok -rescue -noabo -z2p -i 4096000000 -sfsck -senc -p choose savedisk a sda`

i.e. with the `-z2p` option for **parallel bzip2** compression (see also https://github.com/rescuezilla/rescuezilla/issues/290). Could you maybe add this compression option?

Many thanks!!

**Comment by kerstin921** [comment]
**Hello???**

**Comment by fiddyschmitt** [comment]
Hi kerstin, apologies - I must have missed this post. Thanks for the information. I'll make the program support bzip2.

**Comment by kerstin921** [comment]
Hi,

okay, thanks a lot, this is awesome. Great tool, covers the one painfully missing functionality of `clonezilla`

**Comment by fiddyschmitt** [comment]
Almost there Kerstin, just testing today so it'll be available this weekend.

**Comment by fiddyschmitt** [comment]
Hi Kerstin, [version 1.6.0](https://github.com/fiddyschmitt/clonezilla-util/releases/tag/v1.6.0) is ready. Please let me know if it works for your bzip2 clonezilla image.
Cheers :)
Fidel
