### ISSUE TITLE
Doesn't appear to work with older CloneZilla 

### ISSUE THREAD

**Issue by techidad64** [fiddyschmitt/clonezilla-util#52]
I needed to image an older computer and had to use an i486 version of Clonezilla.   It does not appear that the older version creates the
Info-img-id.txt file in the clonezilla folder.    When running clonezilla-util against this image folder, I get the following error.

Unhandled exception. System.IO.FileNotFoundException: Could not find file 'E:\<image folder>\Info-img-id.txt'.
File name: 'E:\<image folder>\Info-img-id.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
   at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 )
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String , Encoding , Int32 )
   at System.IO.File.InternalReadAllLines(String , Encoding )
   at System.IO.File.ReadAllLines(String )
   at libClonezilla.Cache.ClonezillaCacheManager.GetPartitionCache(String partitionName)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__1(String partitionName)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)

Can you help me?

**Comment by fiddyschmitt** [comment]
Hi Techi,

Thanks for reporting it :)

`Info-img-id.txt` is used to work out a unique Id for the archive, for caching purposes. The content doesn't really matter, so you could use [this one](https://github.com/fiddyschmitt/clonezilla-util/files/11360398/Info-img-id.txt) and it should work.
