### ISSUE TITLE
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.

### ISSUE THREAD

**Issue by zenbooster** [fiddyschmitt/clonezilla-util#6]
Hello.
On windows 10 pro, runned with administrator privileges:
```
C:\distrib\clonezilla-util.v1.5.3.win-x64>clonezilla-util.exe mount --input d:\2022-06-24-12-img --mount z:\
[15:39:50 INF] clonezilla-util v1.5.3
[15:39:53 INF] [2022-06-24-12-img] [sda1] Finding optimal decompressor (seekable/sequential)
[15:39:53 INF] [2022-06-24-12-img] [sda1] Loading partition information
[15:39:56 INF] [2022-06-24-12-img] [sda2] Finding optimal decompressor (seekable/sequential)
[15:40:23 INF] [2022-06-24-12-img] [sda2] Loading partition information
[15:40:25 INF] [2022-06-24-12-img] [sda5] Finding optimal decompressor (seekable/sequential)
[15:40:35 INF] [2022-06-24-12-img] [sda5] Loading partition information
[15:40:36 INF] Waiting for z:\ to be available.
```
Endless waiting...

**Comment by zenbooster** [comment]
After install dokan driver:

```
C:\distrib\clonezilla-util.v1.5.3.win-x64>clonezilla-util.exe mount --input d:\2022-06-24-12-img --mount z:\
[16:05:06 INF] clonezilla-util v1.5.3
[16:05:06 INF] [2022-06-24-12-img] [sda1] Finding optimal decompressor (seekable/sequential)
[16:05:07 INF] [2022-06-24-12-img] [sda1] Loading partition information
[16:05:07 INF] [2022-06-24-12-img] [sda2] Finding optimal decompressor (seekable/sequential)
[16:05:18 INF] [2022-06-24-12-img] [sda2] Loading partition information
[16:05:19 INF] [2022-06-24-12-img] [sda5] Finding optimal decompressor (seekable/sequential)
[16:05:29 INF] [2022-06-24-12-img] [sda5] Loading partition information
[16:05:30 INF] Waiting for z:\ to be available.
[16:05:31 INF] [2022-06-24-12-img] [sda1] Retrieving a list of files.
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& )
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle , Boolean& )
   at Interop.Kernel32.SetEvent(SafeWaitHandle )
   at System.Threading.EventWaitHandle.Set()
   at libCommon.ProcessUtility.<>c__DisplayClass0_0.<RunCommand>b__1(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String )
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean )
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by fiddyschmitt** [comment]
Hi zen,

Just confirming - did you install version 1.5.1.1000 of Dokan? Available [here](https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000)?

If so, could you please post the content of `clonezilla-img`.

Thanks!
Fidel

**Comment by fiddyschmitt** [comment]
Hi zen,

Have you tried using this version of the dokan driver?

https://github.com/dokan-dev/dokany/releases/tag/v1.5.1.1000

Thanks,
Fidel

**Comment by zenbooster** [comment]
Yes, that's the version I used. Just started the mount process on another machine, also Windows 10. I'll let you know the results.

**Comment by zenbooster** [comment]
```
[14:01:16 INF] Indexed 295 GB / 295,1 GB (100%)
[14:01:17 INF] Indexed 295,1 GB / 295,1 GB (100%)
[14:01:17 INF] Indexed 295,1 GB / 295,1 GB (100%)
[14:01:17 INF] Indexed 295,1 GB / 295,1 GB (100%)
ERROR: Compressed data error in STDIN.


[14:01:17 INF] Finished generating gzip index. Moving to final location: D:\Distrib\clonezilla-util\clonezilla-util.v1.5.4.win-x64\cache\c41e42060d6ab5c5\sda5.gztool_index.gzi
[14:01:33 INF] [2022-06-24-12-img] [sda5] Loading partition information
[14:01:40 INF] [2022-06-24-12-img] [sda5] Reading partclone content map
[14:01:48 INF] Waiting for g:\ to be available.
[14:01:48 INF] [2022-06-24-12-img] [sda1] Retrieving a list of files.
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& )
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle , Boolean& )
   at Interop.Kernel32.SetEvent(SafeWaitHandle )
   at System.Threading.EventWaitHandle.Set()
   at libCommon.ProcessUtility.<>c__DisplayClass0_0.<RunCommand>b__1(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.Process.ErrorReadNotifyUser(String )
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean )
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[14:01:49 INF] [2022-06-24-12-img] [sda1] 7z.exe will be used to extract files from this partition.
[14:01:49 INF] [2022-06-24-12-img] [sda2] Retrieving a list of files.

D:\Distrib\clonezilla-util\clonezilla-util.v1.5.4.win-x64>
```

**Comment by fiddyschmitt** [comment]
Thanks zen, looking into it now

**Comment by fiddyschmitt** [comment]
Hi zen,

I've just uploaded clonezilla-util v1.5.5, which ignores the 'Safe handle has closed' exception. Could you please let me know if it improves things for you?

Thanks,
Fidel
