### ISSUE TITLE
Missing compression algorithm (lz4)

### ISSUE THREAD

**Issue by playday3008** [fiddyschmitt/clonezilla-util#9]
Hi,

I'm getting an unknown compression error:
```
clonezilla-util.exe mount --input E:\2022-09-04-12-Windows-10-img\ --mount L:\
[14:32:30 INF] clonezilla-util v1.7.1
Unhandled exception. System.Exception: Could not determine compression used by partition sdc1.*-ptcl-img in: E:\2022-09-04-12-Windows-10-img\
   at libClonezilla.PartitionContainers.ClonezillaImage.GetCompressionInUse(String clonezillaArchiveFolder, String filenamePattern)
   at libClonezilla.PartitionContainers.ClonezillaImage.<>c__DisplayClass3_0.<.ctor>b__2(String partitionName)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable )+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 )
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.ClonezillaImage..ctor(String clonezillaArchiveFolder, IClonezillaCacheManager cacheManager, List`1 partitionsToLoad, Boolean willPerformRandomSeeking)
   at libClonezilla.PartitionContainers.PartitionContainer.FromPath(String path, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at libClonezilla.PartitionContainers.PartitionContainer.<>c__DisplayClass8_0.<FromPaths>b__0(String path)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 )
   at libClonezilla.PartitionContainers.PartitionContainer.FromPaths(List`1 paths, String cacheFolder, List`1 partitionsToLoad, Boolean willPerformRandomSeeking, IVFS vfs)
   at clonezilla_util.Program.MountAsFiles(MountAsFiles mountAsFilesOptions)
   at clonezilla_util.Program.Run(Object obj)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at clonezilla_util.Program.Main(String[] args)
```

**Comment by fidel-planbuddies** [comment]
Thanks PlayDay, I'll add LZ4 support in the next week or so.
